### ISSUE TITLE
外置表单中文乱码

### ISSUE THREAD

**Issue by hellolyz** [henryyan/kft-activiti-demo#67]
![default](https://user-images.githubusercontent.com/15335875/29509890-61946cf6-868c-11e7-929f-7b258f91f556.png)
另外，修改了leave-formkey.bpmn文件中activiti:formKey对外置表单的引用，发现项目运行时没有改变引用

**Comment by beyondyinjl** [comment]
在调用的方法上加返回类型和编码如下：
produces = "text/plain;charset=utf-8"

**Comment by hellolyz** [comment]
谢谢
