### ISSUE TITLE
默认是H2数据库，怎么改为mysql数据库？

### ISSUE THREAD

**Issue by wellway** [henryyan/kft-activiti-demo#73]
默认是H2数据库，怎么改为mysql数据库？

**Comment by xiaogong110110** [comment]
我没来的急看，这是我fork进来的

**Comment by henryyan** [comment]
demo内置了h2和mysql两个数据库配置，具体可以查看pom.xml中最后的profile部分，默认h2

* 可以将一下配置从h2移动到mysql部分

```xml
<activation>
    <activeByDefault>true</activeByDefault>
</activation>
```

* 如果在IDE中启动可以用maven工具勾选`mysql`
